<h2>Now VC driven....</h2>
<p>This is just a personal <i class="pop">playground</i> for :</p>
  <ul>
    <li><abbr title = "HyperText Markup Language">HTML</abbr> <num>5</num>,</li>
    <li><i class="pop">contemporary</i> <abbr title = "Cascading Style Sheets">CSS</abbr></li>    
    <li><i class="pop">contemporary</i> <abbr title = "European Computer Manufacturers Association">ECMA</abbr>Script</li>
    <li><i class="pop">assisted</i>  by :
        <ul>
            <li> some additional <abbr title = "PHP Hypertext Preprocessor">PHP</abbr> 8.2+ stuff
              for basic <abbr title="Model-View-Controller">MVC</abbr>-like functionality and dynamic creation of static file resources (HTML, ECMAScript, CSS etc... )<br> from (open | free available | self created) data sources</li></ul>
            </li>

        </ul> 
    </li>
  </ul>
  <p>Audiatur et <mark>altera</mark> pars</p>
  <p>Please press:<br> <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>D</kbd> + <kbd>I</kbd> + <kbd>Ü</kbd> for deleting the Internet temporary <strong> or</strong><br>

  <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>D</kbd> + <kbd>I</kbd> + <kbd>ß</kbd> + <kbd>Ä</kbd> for persisting its death
</p>
<p class="STDOUT"><samp><num title="status code">200.42</num> Internet destroyed successfully!<br>Press <kbd>ALT</kbd> + <kbd>F4</kbd>  to rebuild</samp></p>

  <p>
    <code> GET / HTTP/2.3</code>
    <br>
    <br>
    <p class="STDOUT"><samp><num title="status code">419.23</num> <span title="message">I am a <i>coffee<i>mug</span>!</samp></p>
</p>
<section>
<pre>
<samp><span class="prompt">sven@Marvell Html5_Lab % </span> <kbd>md5 -s "FuckYou"</kbd>
MD5 ("FuckYou") = 3f25560cd9ece0822ce01a77cd1b58e1
<span class="prompt">sven@Marvell</span> <span class="cursor">█</span></samp></pre>
</section>
<p><s>Norman killed Gwen</s></p>

<p>No, Peter did it!</p>
<p>“Did you see God?”</p>
<p><del>“He told me …”</del>
<ins cite="../trivia/god" datetime="2018-05">
    “Yes, she is black”</ins>
</p>
<article>
  <h2>We are in need of essentially more <code>substr(0, $quadrupeld)</code> alliteration...</h2>
  <p><cite class="pop"><a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/document_role">The document role is for the top <mark>cont</mark>ainer <mark>cont</mark>aining <mark>cont</mark>ent that assistive …</a></cite></p>
</article>
<table>
    <caption>Superheros and sidekicks</caption>
    <colgroup>
        <col>
        <col span="2" class="batman">
        <col span="2" class="flash">
    </colgroup>
    <tr>
        <td> </td>
        <th scope="col">Batman</th>
        <th scope="col">Robin</th>
        <th scope="col">The Flash</th>
        <th scope="col">Kid Flash</th>
    </tr>
    <tr>
        <th scope="row">Skill</th>
        <td>Smarts</td>
        <td>Dex, acrobat</td>
        <td>Super speed</td>
        <td>Super speed</td>
    </tr>
    <tr>
        <td> </td>
        <th scope="col">Batman</th>
        <th scope="col">Robin</th>
        <th scope="col">The Flash</th>
        <th scope="col">Kid Flash</th>
    </tr>
    <tr>
        <th scope="col">Skill</th>
        <td>Smarts</td>
        <td>Dex, acrobat</td>
        <td>Super speed</td>
        <td>Super speed</td>
    </tr>
</table>