<h2>Now VC driven....</h2>
<p>This is just a personal <i class="pop">playground</i> for :</p>
  <ul>
    <li><abbr title = "HyperText Markup Language">HTML</abbr> <num>5</num>,</li>
    <li><i class="pop">contemporary</i> <abbr title = "Cascading Style Sheets">CSS</abbr></li>    
    <li><i class="pop">contemporary</i> <abbr title = "European Computer Manufacturers Association">ECMA</abbr>Script</li>
    <li><i class="pop">assisted</i>  by :
        <ul>
            <li>some additional <abbr title = "PHP Hypertext Preprocessor">PHP</abbr> 8.2+ stuff</li>
        </ul> 
    </li>
  </ul>
  
  <p><num title="status code">419.23</num> <span title="message">I am a <i>coffee<i>mug</span>!</p>
  <footer>Nuff said for now & Glück auf! <br>Sven</footer>