<h2>Now VC driven....</h2>
<p>This is just a personal <i class="pop">playground</i> for :</p>
  <ul>
    <li><abbr title = "HyperText Markup Language">HTML</abbr> <num>5</num>,</li>
    <li><i class="pop">contemporary</i> <abbr title = "Cascading Style Sheets">CSS</abbr></li>    
    <li><i class="pop">contemporary</i> <abbr title = "European Computer Manufacturers Association">ECMA</abbr>Script</li>
    <li><i class="pop">assisted</i>  by :
        <ul>
            <li> some additional <abbr title = "PHP Hypertext Preprocessor">PHP</abbr> 8.2+ stuff
              for basic <abbr title="Model-View-Controller">MVC</abbr>-like functionality and dynamic creation of static file resources (HTML, ECMAScript, CSS etc... ) from (open | free available | self created) data </li></ul>
            </li>

        </ul> 
    </li>
  </ul>
  <details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>
<menu>
  <li><button onclick="copy()">Copy</button></li>
  <li><button onclick="cut()">Cut</button></li>
  <li><button onclick="paste()">Paste</button></li>
</menu>
<?= $this->renderDoclet('Widgets/Blockquote')?>
  <p>
    <code> GET / HTTP/2.3
    <br>
    <br>
    <code><num title="status code">419.23</num> <span title="message">I am a <i>coffee<i>mug</span>!</code>
</p>
  <footer>Nuff said for now & Glück auf! <br>Sven</footer>