<form id="calc" class="calculator" onsubmit="return false;">
	<label id="X_label" title="X register of stack"> X <output id="register_X">0.12334545668673</output><label>
	 <hr><br>
     
		<button class="calcKey">Enter</button>
		<button class="calcKey">±</button>
		<button class="calcKey">EEX</button>
		<button class="calcKey">DEL</button>
		<button class="calcKey">⇦</button>
		<button class="calcKey"></button>
		<button class="calcKey"></button>
		<button class="calcKey"></button>
        <br>
        <button class="calcKey">α</button>
        <button class="calcKey">7</button>
		<button class="calcKey">8</button>
		<button class="calcKey">9</button>
		<button class="calcKey"> ÷ </button>
        <br>
		<button class="calcKey">4</button>
		<button class="calcKey">5</button>
		<button class="calcKey">6</button>
		<button class="calcKey">X</button>
        <br>
		<button class="calcKey">1</button>
		<button class="calcKey">2</button>
		<button class="calcKey">3</button>
		<button class="calcKey">-</button>
        <br>
		<button class="calcKey">0</button>
		<button class="calcKey">.</button>
		<button class="calcKey">=</button>
		<button class="calcKey">÷</button>
	 
</form>