<h2> Forms Doclet example</h2>
<!-- Form which will send a POST request to the current URL -->
<form method="post">
  <label>Your first name:
    <input name="first_name" list="first_names" />
    <?= $this->renderDoclet('Forms/Datalist.first'); ?>
  </label>
  <button>Save</button>
</form>

<!-- Form which will send a POST request to the current URL -->
<form method="post">
  <label>Name:
    <input name="submitted-name" autocomplete="name" />
  </label>
  <button>Save</button>
</form>

<!-- Form with fieldset, legend, and label -->
<form method="post">
  <fieldset>
    <legend>Do you agree to the terms?</legend>
    <label><input type="radio" name="radio" value="yes" /> Yes</label>
    <label><input type="radio" name="radio" value="no" /> No</label>
  </fieldset>
</form>
