<!DOCTYPE html>
<html lang="<?=$this->lang?>">
<head>
<title>HTML5_Lab - "<?=$this->subtitle?>"</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="Keywords" content="<?=$this->keywords?>">
  <meta name="Description" content="<?=$this->description?>">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=crimson">
  <link rel="stylesheet" href="/style/main.css"/>
</head>
<body>
  <head><h1>HTML5_Lab - <?=$this->subtitle?></h1></head>
    <?=$this->mainContent?>
  <footer>rendered in <?=$this->rendertime?> seconds <time datetime="<?=$this->now?>"><?=$this->now?></footer>
</body>
</html>